FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080

# after extensive reserach, discovered i need those
ENV ASPNETCORE_ENVIRONMENT="Development"
ENV ASPNETCORE_URLS=http://0.0.0.0:8080

# debug purposes
# RUN apt-get update && apt-get upgrade -y && apt-get install curl net-tools -y && netstat -tlnp

# Define the entry point for the container
ENTRYPOINT ["dotnet"]
CMD ["MagicVilla_VillaAPI.dll"]