apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}:{{ .Values.app.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
