apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}:{{ .Values.app.tag }}
          # override docker CMD
          # args: ["--bind", "0.0.0.0:3000", "book_shop.wsgi:application"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
