aws_region          = "us-east-1"
project_name        = "MagicVilla"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
availability_zone   = "us-east-1a"
instance_type       = "t2.micro"
key_name            = "feb-project"  # Name of your existing EC2 key pair
root_volume_size    = 8
allowed_ssh_cidr    = ["0.0.0.0/0"]  # Replace with your IP!
ecr_repository_name = "MagicVilla"
ami_id = "ami-0b6c6ebed2801a5cb"