name: CICD Dev

on:
    workflow_dispatch:

env:
  BUCKET_NAME: "aseelmalkawi"
  PROJECT_NAME: EFE

jobs:
    prepare: 
      runs-on: [self-hosted]
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Extract Version
          run : | 
              chmod +x common/version_extract.sh
              ./common/version_extract.sh

        - name:  Debugging the extracted Version
          run: echo $VERSION

        - name: Upload Version artifact
          uses: actions/upload-artifact@v4
          with:
            name: version
            path: version.yaml

    build:
      runs-on: [self-hosted]
      needs: prepare
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: version

        - name: Load version into enviroment
          run: |
              chmod +x common/load_version.sh
              ./common/load_version.sh

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '7.0.x'

        - name: Package/Publish app artifact
          run: |
              dotnet restore
              dotnet publish -c Release -o ./app/publish

        - name: Push artifact to S3
          run: s3 sync

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: app-build
            path: app
    docker:
        needs: build
        runs-on: [self-hosted]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download artifact 
              uses: actions/download-artifact@v4
              with:
                name: app-build

            - name: Download app artifact from S3
              run: |
                  chmod +x common/extract_artifact.sh
                  ./common/extract_artifact.sh   
                
            - name: Login into AWS ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: version

            - name: Load version into enviroment
              run: |
                chmod +x common/load_version.sh
                ./common/load_version.sh

            - name: Debugging the extracted Version
              run: echo $VERSION

            - name: Build and push Image 
              uses: docker/build-push-action@v6 
              with:
                context: .
                file: ./Dockerfile-stage2
                push: true
                tags: ${{ secrets.ECR_URI }}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}
      
    deploy:
      runs-on: [self-hosted]
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: version

        - name: Load version into enviroment
          run: |
            chmod +x common/load_version.sh
            ./common/load_version.sh
        
        # - name: ssm command