name: CICD Prod

on:
    workflow_dispatch:

env:
  PROJECT_NAME: magic-villa

jobs:
    promote:
      runs-on: [self-hosted]
      outputs:
        BASE_TAG: ${{ steps.promote.outputs.BASE_TAG }}
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name : Config AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-1
            
        - name: Login into AWS ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Load Outputs
          run: |
            chmod +x common/load_outputs.sh
            ./common/load_outputs.sh

        - name: Promote script
          id: promote
          run: |
            chmod +x common/promote.sh
            ./common/promote.sh
      
    deploy:
      runs-on: [self-hosted]
      needs: promote
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Extract Version
          run : | 
              chmod +x common/version_extract.sh
              ./common/version_extract.sh

        - name: Load Outputs
          run: |
            chmod +x common/load_outputs.sh
            ./common/load_outputs.sh
        
        - name: Configure kubeconfig
          run: |
            mkdir -p ~/.kube
            echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
            chmod 600 ~/.kube/config

        - name: Deploy
          run: |
            helm upgrade --install magicvilla ./helm \
              -f helm/values.yaml \
              --set app.image=${{ env.ECR_URI }} \
              --set app.tag=${{ env.VERSION }} \
              --wait \
              --timeout 5m

        - name: Verify deployment
          run: |
            microk8s kubectl rollout status deployment/${ env.PROJECT_NAME }