name: Create Infra

on:
    workflow_dispatch:

jobs:
    Terraform: 
        runs-on: [self-hosted]
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: init
          run: |
            cd terraform
            terraform init -backend-config=backend-config.hcl
            terraform plan
        
        - name: apply
          run: |
            cd terraform
            terraform apply --auto-approve
    Ansible: 
        runs-on: [self-hosted]
        needs: Terraform
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Write SSH key
          run: |
            echo "${{ secrets.KEY }}" > /tmp/deploy_key
            chmod 600 /tmp/deploy_key

        - name: Write inventory
          run: |
            cat > Ansible/inventory.yml <<EOF
            all:
              hosts:
                my_server:
                  ansible_host: $(terraform output -raw server_ip)
                  ansible_user: ubuntu
                  ansible_ssh_private_key_file: /tmp/deploy_key
            EOF

        - name: Debug inventory
          run: cat Ansible/inventory.yml && echo "---" && ansible-inventory -i Ansible/inventory.yml --list

        - name: ansible configuration
          run: |
            ansible-playbook -i Ansible/inventory.yml Ansible/setup.yml